openapi: 3.0.0
info:
  title: Holoapi
  version: v1
tags: []
components:
  schemas:
    Video:
      type: object
      properties:
        id:
          type: integer
        yt_video_key:
          type: string
        bb_video_id:
          type: string
        title:
          type: string
        thumbnail:
          type: string
        live_schedule:
          type: string
        live_start:
          type: string
        live_end:
          type: string
        live_viewers:
          type: string
        channel:
          $ref: "#/components/schemas/Channel"
          required: false
        comments:
          type: array
          items:
            $ref: "#/components/schemas/Comment"

    Channel:
      type: object
      properties:
        id:
          type: integer
        yt_channel_id:
          type: string
        bb_space_id:
          type: string
        name:
          type: string
        description:
          type: string
        photo:
          type: string
          example: "https://yt3.ggpht.com/a/AATXAJw7R8J8buhX7Cw1m63vK2jlKFv-9YhFf-TQaA=s800-c-k-c0xffffffff-no-rj-mo"
        published_at:
          type: string
        twitter_link:
          type: string
          example: yuzukichococh

    Comment:
      type: object
      properties:
        comment_key:
          type: string
          description: >-
            "the youtube comment ID of the comment,
            use this comment_key along with the video to generate a direct link to the comment."
        message:
          type: string
          description: >-
            plain text of a comment.


paths:
  /live:
    get:
      description: Fetches videos that are currently live.
      responses:
        200:
          description: SUCCESS
          content:
            application/json:
              schema:
                type: object
                properties:
                  live:
                    type: array
                    items:
                      $ref: "#/components/schemas/Video"
                  upcoming:
                    type: array
                    items:
                      $ref: "#/components/schemas/Video"
                  ended:
                    type: array
                    items:
                      $ref: "#/components/schemas/Video"
                  cached:
                    type: boolean
                    description: whether the response was cached or not
  /comments/search:
    get:
      description: Search for videos containing timestamped comment that has the query keyword
      parameters:
        - name: q
          description: >-
            Query to search. This Query will be sanitized and returned back to you, since all the comment strings in the db have been sanitized.
            There are no full width alphanumerics or half width kana characters.
          in: query
          schema:
            type: string
            example: Kimi no Shiranai
          required: true
        - name: limit
          description: The number of videos to return.
          in: query
          required: false
          schema:
            type: integer
            default: 25
            maximum: 50
        - name: offset
          description: The number of videos to skip.
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: channel_id
          description: a channel_id, this is a numerical id obtained from the /channels endpoint that uniquely identifies the channel on our platform. Does not support youtube/other channel hash.
          in: query
          required: false
          schema:
            type: integer
            default: null
      responses:
        "200":
          description: returns search result
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: list of videos along with their channel and all the timestamp comments
                    items:
                      $ref: "#/components/schemas/Video"
                  count:
                    type: integer
                    description: count of total number of videos
                  cached:
                    type: boolean
                    description: whether it's returning you a cached result.
                  query:
                    type: string
                    description: >-
                      A post-sanitized query text. This query is probably more likely than the input parameter q? to have
                      matches in the comments.
